name: Build

on: [push, pull_request]

jobs:
  handle_forks:
    name: Forked Repo
    runs-on: ubuntu-latest
    if: github.repository != 'HandBrake/HandBrake-docs'
    steps:
    - name: Print Warning
      run: |
        echo "Builds are disabled for forked repositories."      

  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    if: github.repository == 'HandBrake/HandBrake-docs'
    steps:
    - uses: actions/checkout@master
    
    - name: Toolchain Cache
      id: build-toolchain
      uses: actions/cache@v1
      with:
        path: tools/local
        key: build-toolchain
        
    - name: Build Toolchain
      if: steps.build-toolchain.outputs.cache-hit != 'true'
      run: |
        git submodule update --init
        ./build-tools 
        ls -la
        
    - name: Build
      run: |
        bash ./marsh build --markdown="tools/local/bin/markdown"

    - uses: actions/upload-artifact@master
      with:
         name: docs
         path: public/
